### ISSUE TITLE
Segmentation Fault when finetuning or decoding using WEBNLG

### ISSUE THREAD

**Issue by lesliecasas** [UKPLab/plms-graph2text#2]
I am running the repository without any changes: 1) preprocessing_WEBNLG.sh 2) finetune_WEBNLG.sh
1) runs normally 
![image](https://user-images.githubusercontent.com/26875383/104048612-d05b4300-51e3-11eb-9bee-48e5736ca9d6.png)

But I get a "Segmentation fault error" in 2). It comes in the super().__init__() of BaseTransformer Class. "1894 Segmentation fault      (core dumped) ". It means the the error is back in th LightningModule.
![image](https://user-images.githubusercontent.com/26875383/104046358-4067ca00-51e0-11eb-8246-14b897781b6d.png)

I have used the original webnlg repository https://gitlab.com/shimorina/webnlg-dataset (folder webnlg_challenge_2017) as input.

Where could be the problem?
Thanks
Leslie

Here some details: Run in docker container
Ubuntu 18.04.4 LTS
GeForce RTX 2080 
CUDA  11.0
Python 3.6.9
transformers 3.3.1
torch 1.4.0
pytorch-lightning  0.9.0
parsimonious 0.8.1
rouge-score 0.0.4
sacrebleu 1.4.14

**Comment by shixiao9941** [comment]
I also met this problem when ran the code,  it was because of the CUDA version on your machine. I firstly used 11.0, it shows 'segmentation fault', but when I switch to another machine whose CUDA version is 10.2, it works.

**Comment by leoribeiro** [comment]
Hi @lesliecasas, for this project I used the  CUDA 10.0 (cudatoolkit 10.0.130). I think his error is related to the CUDA version, as Xiao has mentioned:  "also met this problem when ran the code, it was because of the CUDA version on your machine. I firstly used 11.0, it shows 'segmentation fault', but when I switch to another machine whose CUDA version is 10.2, it works."
